services:
  image-api:
    image: image-api
    build: .
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - ./uploads:/app/uploads # Para persistir las imágenes subidas
      - ./temp:/app/temp
    restart: unless-stopped
